INSERT INTO TB_DIRETOR
     (NUMERO, NOME)
  VALUES
     (11, 'Jair Menalau Bartolomeu');

INSERT INTO TB_DIRETOR
     (NUMERO, NOME)
  VALUES
     (12, 'Paulo Gustavo');

INSERT INTO TB_ADMINISTRATIVO
     (NUMERO, NOME)
  VALUES
     (31, 'Marcos Petra');

INSERT INTO TB_ADMINISTRATIVO
     (NUMERO, NOME)
  VALUES
     (32, 'Tarcisio Hammer');

INSERT INTO TB_VEICULO
    (ID, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR)
   VALUES
    (1, 'FORD', 'FIESTA', 2009, 2009, 'PRATA');

INSERT INTO TB_VEICULO
    (ID, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR)
   VALUES
    (2, 'VW', 'FUSCA', 1986, 1986, 'PRETO');



